/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotest.ci.sample

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe


class AppTest : FunSpec() {
    init {
        context("正常系") {
            val calc = Calc(1, 1)
            calc.add() shouldBe 2
        }
    }
}
