/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotest.ci.sample

/**
 * 計算クラス
 */
class Calc(
    private val num1: Int,
    private val num2: Int
) {
    /**
     * num1 と num2 を加算します。
     *
     * @return num1 と num2 の加算の結果
     */
    fun add(): Int {
        return num1 + num2
    }
}

fun main() {
    val calc = Calc(1, 1)
    print("1 + 1 = ${calc.add()}")
}
